config/routes.rb
Rails.application.routes.draw do

  get '/signup', to: 'users#new' 
  post '/users', to: 'users#create'

  get '/signin', to: 'users#signin'
  post '/signin', to: 'users#authenticate'

  resources :users, only: [:show] do
    resources :appointments, only: [:index]
    resources :registrations, only: [:index, :update]
    resources :pets, only: [:index, :new, :create] do
      resources :registrations, only: [:new, :create] do
        resources :appointments , only: [:new, :create]
      end
    end
  end
  get '/users/:id/pets', to: 'pets#index'

  root "users#signin"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_user, only: [:new, :index]

  def create 
    response = VetsApi::Appointment.new(cookies[:token], params:appointment_params).create_appointment
    if response.created?
      @user = response.parsed_response
      redirect_to user_pets_path(@user['id'])  
    else 
      @user = VetsApi::User.new(cookies[:token]).get_user
      flash.now[:alert] = 'Couldnt create Appointment'
      render :new, status: :unprocessable_entity
    end
  end

  private
  def appointment_params
    params.permit(:date, :pet_id, :registration_id)
  end

  def set_user
    response = VetsApi::User.new(token = cookies[:token]).get_user 
    @user = response.parsed_response
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController  
  before_action :set_user, only: [:index, :new]
  
  def create
    response = VetsApi::Pet.new(cookies[:token], params: pet_params).create_pet
    if response.created?
      @user = response.parsed_response
      flash[:notice] = 'Created pet'
      redirect_to user_pets_path(@user['id'])  
    else 
      @user = VetsApi::User.new(cookies[:token]).get_user
      flash.now[:alert] = 'Couldnt create pet'
      render :new, status: :unprocessable_entity
    end
  end

  private
  def pet_params
    params.permit(:name, :animal)
  end

  def set_user
    response = VetsApi::User.new(cookies[:token]).get_user
    @user = response.parsed_response
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_user, only: [:index, :new]

  def new 
    @vets = VetsApi::User.new(cookies[:token]).get_vets
  end
  
  def create
    response = VetsApi::Registration.new(cookies[:token], params: registration_params ).create_registration
    if response.created?
      @user = response.parsed_response
      redirect_to user_pets_path(@user['id'])  
    else 
      @user = VetsApi::User.new(cookies[:token]).get_user
      flash.now[:alert] = 'Couldnt create registration'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    response = VetsApi::Registration.new(cookies[:token], params: registration_params).accept_registration
    if response.success?
      @user = response.parsed_response
      flash[:notice] = 'Accepted registration'
      redirect_to user_registrations_path(@user['id'])  
    else  
      @user = VetsApi::User.new(cookies[:token]).get_user
      flash.now[:alert] = 'Couldnt accept registration'
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def registration_params
    params.permit(:vet_email, :pet_id, :id)
  end

  def set_user
    response = VetsApi::User.new(cookies[:token]).get_user
    @user = response.parsed_response
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    response = VetsApi::User.new(params: user_params).create_user
    if response.created?
      succesfull_response(response)
    else 
      flash.now[:alert] = 'User couldnt be created'
      render :new, status: :unprocessable_entity
    end
  end

  def authenticate
    response = VetsApi::User.new(params: user_params).authenticate
    if response.success?
      succesfull_response(response)
    else 
      flash.now[:alert] = 'Email or password incorrect'
      render :signin, status: :unauthorized
    end 
  end

  def show
    response = VetsApi::User.new(cookies[:token]).get_user
    @user = response.parsed_response
  end

  private
  def user_params
    params.permit(:name, :email, :password, :role)
  end

  def succesfull_response(response)
    @user = response.parsed_response
    cookies[:token] = @user['auth_token']
    redirect_to user_path(@user['id']) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/index.html.slim
= render partial: 'layouts/nav' 

=turbo_frame_tag 'content'
  div class='page-body' 
    div class='mx-4'
      h1 Apointments
    div class='card'
      ul
        - @user['pets'].each do |pet|
          - pet['registrations'].each do |registration|
            - registration['appointments'].each do |appointment|
              li #{appointment['date'].to_time.strftime('%d %B - %H:%M')} - #{pet['name']}


      
    

app/views/appointments/new.html.slim
= render partial:'layouts/nav'
= turbo_frame_tag 'content'
  div class='page-body'
    div class='flex flex-col w-full mt-28'
      div class='flex justify-center'
        h1 New Appointment
      div class='w-full flex justify-center'
        = form_with url:"/users/#{params[:user_id]}/pets/#{params[:pet_id]}/registrations/#{params[:registration_id]}/appointments", local:true, class: 'w-full' do |form|
          div class='my-4'
            = form.label :date
            br/
            = form.date_field :date
          div
            = form.submit 'Make Appointment', class:'btn btn-form btn-lg w-full'

app/views/layouts/_flash.html.slim
  - if flash[:notice]
    div class='notice'
      h3 #{flash[:notice]}
  - if flash[:alert]
    div class='alert'
      h3 #{flash[:alert]}

app/views/layouts/_nav.html.slim
div class='flex flex-col sidenav '
  ul
    li class='nav-item flex align-center  mx-1 my-1 py-1'
      = link_to 'User-Info', user_path(@user['id']), data:{'turbo_frame':'content', 'turbo_action':'advance'}
    li class='nav-item flex align-center  mx-1 my-1 py-1'
      = link_to 'Pets', user_pets_path(@user['id']), data:{'turbo_frame':'content', 'turbo_action':'advance'}
    - if @user['role'] == 'vet'
      li class='nav-item flex align-center  mx-1 my-1 py-1'
        = link_to 'Registrations', user_registrations_path(@user['id']), data:{'turbo_frame':'content', 'turbo_action':'advance'}
      li class='nav-item flex align-center  mx-1 my-1 py-1'
        = link_to 'Appointments', user_appointments_path(@user['id']), data:{'turbo_frame':'content', 'turbo_action':'advance'}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title ConsumerVetApp
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    main class='container mx-auto mt-0 px-5 flex'
      = yield

app/views/pets/_owner_pet.html.slim
div class='card'
  h2 #{pet['name']}
  hr class='w-full border-t-8 py-2'

  div class='flex'
    h3 class='underline pr-2' Registered Vets
    = link_to 'Register a new vet' , new_user_pet_registration_path(@user['id'], pet['id']) , class:'btn btn-md btn-card', data: {'turbo_action':'advance'}  
  - pet['registrations'].each do |registration|
    - if registration['accepted'] == true
      h4 class='pb-2' Vet: #{registration['user']}
      div class='flex'
        h4 class='underline' Appointments
        = link_to 'Make an appointmet' , new_user_pet_registration_appointment_path(@user['id'], pet['id'], registration['id']), 
          class:'btn btn-md btn-card', 
          data: {'turbo_action':'advance'}  

      -registration['appointments'].each do |appointment|
        div class='flex'
          p class='font-bold py-2' Date and time: 
          p class='py-2' #{appointment['date'].to_time.strftime('%d %B - %H:%M')}
      hr class='border-t-4 py-2'

app/views/pets/_pet.html.slim
div class='card'
  h2 #{pet['name']}
  hr class='w-full border-t-8 py-2'

  div class='flex'
    h3 class='underline pr-2' Registered Vets
    = link_to 'Register a new vet' , new_user_pet_registration_path(@user['id'], pet['id']) , class:'btn btn-md btn-card', data: {'turbo_action':'advance'}  
  - pet['registrations'].each do |registration|
    - if registration['accepted'] == true
      h4 class='pb-2' Vet: #{registration['user']}
      div class='flex'
        h4 class='underline' Appointments
        = link_to 'Make an appointmet' , new_user_pet_registration_appointment_path(@user['id'], pet['id'], registration['id']), 
          class:'btn btn-md btn-card', 
          data: {'turbo_action':'advance'}  

      -registration['appointments'].each do |appointment|
        div class='flex'
          p class='font-bold py-2' Date and time: 
          p class='py-2' #{appointment['date'].to_time.strftime('%d %B - %H:%M')}
      hr class='border-t-4 py-2'

app/views/pets/_vet_pet.html.slim
div class='card'
  h2 #{pet['name']}
  hr class='w-full border-t-8 py-2'

  div class='flex'
    h2 class='underline' Apointments
  - pet['registrations'].each do |registration|
    - if registration['accepted'] == true
      div class='flex' 
      -registration['appointments'].each do |appointment|
        div class='flex'
          p class='font-bold py-2' Date and time: 
          p class='py-2' #{appointment['date'].to_time.strftime('%d %B')}
      hr class='border-t-4 py-2'

app/views/pets/index.html.slim
= render partial: 'layouts/nav'     
=turbo_frame_tag 'content'
  = render partial: 'layouts/flash'
  div class='page-body' 
    div class='flex'
      div class='mx-4'
        h1 Pets
    - if @user['role'] == 'owner'
      - @user['pets'].each do |pet|
        = render 'owner_pet', { pet: pet , user: @user }
      = link_to 'add a pet' ,new_user_pet_path(@user['id']), class:'btn btn-xl btn-form', data: {'turbo_action':'advance'}
    - else 
      - @user['pets'].each do |pet|
        = render 'vet_pet', { pet: pet , user: @user }
    

app/views/pets/new.html.slim
=render partial:'layouts/nav'
      
=turbo_frame_tag 'content'
  = render partial: 'layouts/flash'
  div class='page-body'
    div class='flex flex-col w-full mt-28'
        div class='flex justify-center'
          h1 New Pet
        div class='w-full flex justify-center'
          = form_with url:"/users/#{params[:user_id]}/pets", local:true, class: 'w-full' do |form|
            div class='my-4'
              = form.label :name
              br/
              = form.text_field :name
            div class='my-4'
              = form.label :animal
              br/
              = form.text_field :animal
            div
              = form.submit 'Add Pet', class:'btn btn-form btn-lg w-full'

app/views/users/new.html.slim
div class='flex flex-col w-full mt-28'
  = render partial:'layouts/flash'
  div class='flex justify-center'
    h1 Signup
  div class='w-full flex justify-center'
    = form_with url:'/users', local:true, class: 'w-1/3' do |form|
      div class='my-4'
        = form.label :name
        br/
        = form.text_field :name, class:'dark:bg-gray-200 '
      div class='my-4'
        = form.label :email
        br/
        = form.text_field :email, class:'dark:bg-gray-200 '
      div class='my-4'
        = form.label :role
        br/
        = form.select :role, ['owner','vet'], class:'dark:bg-gray-200 form-select'
      div class='my-4'
        = form.label :password
        br/
        = form.password_field :password, class:'dark:bg-gray-200'
      div
        = form.submit 'signup', class:'btn btn-form btn-lg'
      div class='flex flex-row'
        p class='dark:text-white' already have an account ?
        = link_to 'sign-in', '/signin',class:'link'

app/views/users/show.html.slim
= render partial:'layouts/nav'
= turbo_frame_tag 'content'
  div class='page-body' 
    div class='flex'
      div class='mx-4'
        h1 Name: #{@user['name']}
      - if @user['role'] == 'owner'
        div class='mx-4'
          h1 #{@user['pets'].length} Pets
    div class='card'
      h2 email
      p #{@user['email']}


  
    



    

app/views/users/signin.html.slim
div class='flex flex-col w-full mt-28'
  = render partial:'layouts/flash'
  div class='flex justify-center'
    h1 Signin
  div class='w-full flex justify-center'
    = form_with url:'/signin', local:true, class: 'w-1/3' do |form|
      div class='my-4'
        = form.label :email
        br/
        = form.text_field :email, class:'dark:bg-gray-200 '
      div class='my-4'
        = form.label :password
        br/
        = form.password_field :password, class:'dark:bg-gray-200 '
      div
        = form.submit 'signin', class:'btn btn-form btn-lg'
      div class='flex flex-row'
        p class='dark:text-white' don't have an account ?
        = link_to 'sign-up', '/signup',class:'link' 